# ================================
# Cloud Build configuration for Doctigo Vitals
# Author: Arnab Deb
# Repo: ARNAB131 / Doctigo-Vitals-Forcasting
# ================================

steps:
  # STEP 1 — Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/doctigo-vitals', '.']

  # STEP 2 — Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/doctigo-vitals']

  # STEP 3 — Deploy the built image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'doctigo-vitals',
        '--image', 'gcr.io/$PROJECT_ID/doctigo-vitals',
        '--region', 'asia-south2',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8080',
        '--memory', '2Gi',
        '--cpu', '2'
      ]

images:
  - 'gcr.io/$PROJECT_ID/doctigo-vitals'

# Optional settings (recommended)
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

# Optional substitutions (handy if you want to customize later)
substitutions:
  _SERVICE_NAME: "doctigo-vitals"
  _REGION: "asia-south2"

